#! /bin/sh

xf=10
xy=10
sxf=0
syf=0
xs=40
xs=40
sxs=0
sys=0

function upf()
{
sxf=`expr $sxf + 0.1`
}
function downf()
{
sxf=`expr $sxf - 0.1`
}
function leftf()
{
syf=`expr $syf - 0.1`
}
function rightf()
{
syf=`expr $syf + 0.1`
}

function ups()
{
sxs=`expr $sxs + 0.1`
}
function downs()
{
sxs=`expr $sxs - 0.1`
}
function lefts()
{
sys=`expr $sys - 0.1`
}
function rights()
{
sys=`expr $sys + 0.1`
}

function movef()
{
xf=`expr $xf + $sxf`
yf=`expr $yf + $syf`
echo "$xf $yf" > userf.dat
}
function moves()
{
xs=`expr $xs + $sxs`
ys=`expr $yx + $sys`
echo "$xs $ys" > users.dat
}

funtion judge()
{
if [[ $xf == 0 || $xf == 50]]; then $sxf =`expr -$sxf`

gnuplot <<! 
set terminal pngcairo size 1500,900
set output 'user.png'
unset xtics
unset ytics
unset key
set xrange [0:50]
set yrange [0:50]
plot 'user_f.dat' with circle lc rgb 'green' fs solid 0.5 noborder,\
'user_s.dat' with circle lc rgb 'red' fs solid 0.5 noborder
set output
exit
!
